### ISSUE TITLE
Possible conflict with requirements: players` menu differs from required

### ISSUE THREAD

**Issue by DominikWolek** [DominikWolek/bomberman#32]
![image](https://user-images.githubusercontent.com/34174337/59145542-97defc00-89e5-11e9-95a3-33acf27b646e.png)

![image](https://user-images.githubusercontent.com/34174337/59145534-85fd5900-89e5-11e9-89e9-a624b4952dab.png)

**Comment by rz4b4** [comment]
Fixed the requirement to match the implementation.
