### ISSUE TITLE
Conflict with requirements: delay between close-ins of wall is too short

### ISSUE THREAD

**Issue by DominikWolek** [DominikWolek/bomberman#38]
> Zewnętrzne obrabowanie mapy po 2 minutach od rozpoczęcia rozgrywki zaczyna migać na kolor
czerwony przez 5 sekund, po tym czasie mapa zmniejsza się według poniższego schematu
(stawiane są bloki stałe). Gracz stojący w miejscu zmniejszenia mapy w momencie przemiany w
bloki stałe ginie. Pomiędzy każdym kolejnym zmniejszeniem się mapy występuje odstęp czasowy
wynoszący 30 sekund.

Actually, border of map start blinking red after 45 s (120 s required). After 5 s walls close in. Process repeat every 45 s (30 s required).

**Comment by rz4b4** [comment]
Fixed the requirement to match the implementation.
