### ISSUE TITLE
Can't reach main menu after winning game

### ISSUE THREAD

**Issue by DominikWolek** [DominikWolek/bomberman#40]
As described above.
OS: Ubuntu
Nicknames: `abc123` / `abe123` / `abd123` / `bot3`
![image](https://user-images.githubusercontent.com/34174337/59152486-1323ca80-8a45-11e9-89ca-79b205779c82.png)

**Comment by filipjsowa** [comment]
Fixed e41e53e42a7c4160563c38d0cf513d443e218b8b
