### ISSUE TITLE
Conflict with requirements: wrong color order and default settings 

### ISSUE THREAD

**Issue by DominikWolek** [DominikWolek/bomberman#41]
>   Kolejność kolorów: czerwony, niebieski, zielony, żółty, szary, różowy (czerwony jest
domyślnym kolorem przy pierwszym uruchomieniu, po kolejnych zmianach kolory są zapisywane).

In game implemented order: blue green, yellow, grey, pink, basic, red
Default color: red

**Comment by rz4b4** [comment]
Fixed the requirement to match the implementation.
