### ISSUE TITLE
Conflict with requirement 7.2: sound / music turns on after setting non-zero value

### ISSUE THREAD

**Issue by DominikWolek** [DominikWolek/bomberman#43]
> 7.2.2 Gracz ustawia muzykę/efekty dźwiękowe/oba na "OFF" oraz ustala dowolną
głośność na suwaku głośności muzyki/efektów dźwiękowych/obu (odpowiednio).
7.2.3.1 Jeśli gracz wyciszył muzykę, po rozpoczęciu gry nie będzie jej słychać

It's not possible now to set non-zero value AND keep sound / music OFF.

**Comment by rz4b4** [comment]
Changed 7.2.2 to "Gracz ustawia muzykę/efekty dźwiękowe/oba na "OFF" lub ustala zerową głośność na suwaku głośności muzyki/efektów dźwiękowych/obu (odpowiednio)."
